version: "3.5"
services:
  db:
    image: "postgres:11"
    ports:
      - "5432:5432"
  redis:
    image: "redis:5"
    ports:
      - "6379:6379"
  website:
    build: .
    volumes:
    - .:/signdict:delegated
    depends_on:
      - db
      - redis
    ports:
      - "4000:4000"
    command: sh -c "/signdict/docker-entrypoint.sh"
